"[team] Isotope":
  - "([x] Analytics|[x] Onboarding|[x Homescreen|[x] Customers)"
"[team] Proton":
  - "([x] Customer facing pages|[x] Checkout|[x] Settings or Status|[x] Coupons|[x] Products|[x] Orders|[x] Payments|[x] Rest API)"
