on:
  push:
    branches:    
      - 'try/k6-github-action'

jobs:
    build:
        name: Build zip for PR
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build
              id: build
              uses: woocommerce/action-build@trunk
              env:
                  BUILD_ENV: e2e

            - name: Upload PR zip
              uses: actions/upload-artifact@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  name: woocommerce
                  path: ${{ steps.build.outputs.zip_path }}
                  retention-days: 7

    k6-tests-run:
      name: k6 local test run - basic example
      runs-on: ubuntu-latest
      needs: [build]
      steps:
          - name: Create dirs.
            run: |
                mkdir -p code/woocommerce
                mkdir -p package/woocommerce
                mkdir -p tmp/woocommerce
                mkdir -p node_modules

          - name: Checkout code.
            uses: actions/checkout@v2
            with:
                path: package/woocommerce

          - name: Install PNPM and install dependencies
            working-directory: package/woocommerce
            run: |
                npm install -g pnpm
                pnpm install

          - name: Load docker images and start containers.
            working-directory: package/woocommerce/plugins/woocommerce
            run: pnpx wc-e2e docker:up tests/e2e/docker/init-sample-products.sh

          - name: Move current directory to code. We will install zip file in this dir later.
            run: mv ./package/woocommerce/plugins/woocommerce/* ./code/woocommerce

          - name: Download WooCommerce ZIP.
            uses: actions/download-artifact@v2
            with:
                name: woocommerce
                path: tmp

          - name: Extract and replace WooCommerce zip.
            working-directory: tmp
            run: |
                unzip woocommerce.zip -d woocommerce
                mv woocommerce/woocommerce/* ../package/woocommerce/plugins/woocommerce/

          - name: Install dependencies again
            working-directory: package/woocommerce
            run: |
                npm install -g pnpm
                pnpm install

          - name: Run local k6 test
            uses: k6io/action@v0.1
            with:
              filename: plugins/woocommerce/tests/performance/tests/simple-all-shopper-requests.js
