name: Run code coverage on PR
on:
  pull_request
defaults:
  run:
    shell: bash
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Code coverage (PHP 7.4, WP Latest)
    timeout-minutes: 20
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer
          extensions: mysql
          coverage: none

      - name: Tool versions
        run: |
          php --version
          composer --version

      - name: Get cached composer and pnpm directories
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            ~/.pnpm-store
            plugins/woocommerce/packages
            plugins/woocommerce/**/vendor
          key: ${{ runner.os }}-npm-composer-${{ hashFiles('**/composer.lock', '**/pnpm-lock.yaml') }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Composer dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: pnpm nx composer-install woocommerce
        
      - name: Build Admin feature config
        run: |
          pnpm nx build:feature-config woocommerce

      - name: Run Tests With Code Coverage
        run: |
          cd plugins/woocommerce
          composer require "wp-phpunit/wp-phpunit" "^5.9" --dev --no-scripts
          echo "{ \"phpVersion\": \"7.4\", \"core\": \"WordPress/WordPress#5.9\" }" > .wp-env.override.json
          npm -g install @wordpress/env
          wp-env start
          wp-env run tests-wordpress "chmod 755 wp-content wp-content/plugins wp-content/uploads"
          pnpm nx test-code-coverage woocommerce || true
      
      - name: Send code coverage to Codecov.
        run: |
          bash <(curl -s https://codecov.io/bash)
