name: "Enforce release code freeze"
on:
  schedule:
    - cron: '0 22 * * 4' # Run at 1600 UTC on Thursdays.

jobs:
  maybe-create-next-milestone-and-release-branch:
    name: "Maybe create next milestone and release branch"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer

      - name: Tool versions
        run: |
          php --version
          composer --version

      - name: Get cached composer and pnpm directories
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            ~/.pnpm-store
            plugins/woocommerce/packages
            plugins/woocommerce/**/vendor
          key: ${{ runner.os }}-npm-composer-version-${{ secrets.WORKFLOW_CACHE }}-${{ hashFiles('**/composer.lock', '**/pnpm-lock.yaml') }}

      - name: Install PNPM
        run: npm install -g pnpm@^6.24.2

      - name: Install dependencies
        run: pnpm install

      - name: Install Composer dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: pnpm nx composer-install woocommerce

      - name: "Run the script to enforce the code freeze"
        id: freeze
        run: php .github/workflows/scripts/release-code-freeze.php
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREATE_CHANGELOG_PR: 1
          TIME_OVERRIDE: '2022-05-19 14:00:00'

      - name: "Create Pull Requesst"
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'Generate changelog for ${{ steps.freeze.outputs.release }}'
          
