name: Smoke k6 test daily
on:
  workflow_dispatch:
jobs:
  build:
    name: Build WooCommerce zip
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build
          id: build
          uses: woocommerce/action-build@trunk
          env:
              BUILD_ENV: e2e

        - name: Upload WC zip
          uses: actions/upload-artifact@v2
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              name: woocommerce
              path: ${{ steps.build.outputs.zip_path }}
              retention-days: 7


  update-woocommerce:
    name: Run k6 smoke test using trunk on ext site.
    runs-on: ubuntu-18.04
    needs: [build]
    steps:

      - name: Create dirs.
        run: |
              mkdir -p code/woocommerce
              mkdir -p package/woocommerce
              mkdir -p tmp/woocommerce
              mkdir -p node_modules

      - name: Checkout code.
        uses: actions/checkout@v2
        with:
          path: package/woocommerce
          ref: trunk

      - name: Install prerequisites.
        working-directory: package/woocommerce/plugins/woocommerce
        run: |
          npm install -g pnpm
          pnpm install
          pnpm nx composer-install-no-dev woocommerce
          pnpm nx build-assets woocommerce
          pnpm install jest
          
      - name: Run e2e woocommerce update.
        working-directory: package/woocommerce/plugins/woocommerce
        env:
          SMOKE_TEST_URL: ${{ secrets.SMOKE_TEST_PERF_URL }}
          SMOKE_TEST_ADMIN_USER: ${{ secrets.SMOKE_TEST_PERF_ADMIN_USER }}
          SMOKE_TEST_ADMIN_PASSWORD: ${{ secrets.SMOKE_TEST_PERF_ADMIN_PASSWORD }}
          SMOKE_TEST_ADMIN_USER_EMAIL: ${{ secrets.SMOKE_TEST_ADMIN_USER_EMAIL }}
          SMOKE_TEST_CUSTOMER_USER: ${{ secrets.SMOKE_TEST_CUSTOMER_USER }}
          SMOKE_TEST_CUSTOMER_PASSWORD: ${{ secrets.SMOKE_TEST_CUSTOMER_PASSWORD }}
          WC_E2E_SCREENSHOTS: 1
          E2E_RETEST: 1
          E2E_SLACK_TOKEN: ${{ secrets.SMOKE_TEST_SLACK_TOKEN }}
          E2E_SLACK_CHANNEL: ${{ secrets.SMOKE_TEST_SLACK_CHANNEL }}
          UPDATE_WC: 1
          DEFAULT_TIMEOUT_OVERRIDE: 120000
        run: |
              pnpx wc-e2e test:e2e tests/e2e/specs/smoke-tests/update-woocommerce.js
